### ISSUE TITLE
Umbrella: Delete unsupported things from the DB

### ISSUE THREAD

**Issue by kulla** [serlo/db-migrations#188]
- [ ] https://github.com/serlo/db-migrations/issues/187
- [ ] https://github.com/serlo/db-migrations/issues/189
- [ ] https://github.com/serlo/db-migrations/issues/190

**Comment by kulla** [comment]
We use labels now in the project for a better overview
