### ISSUE TITLE
`GroupedExercise`: copy into state of `ExerciseGroup`

### ISSUE THREAD

**Issue by elbotho** [serlo/db-migrations#252]
(I'm using `GroupedExercise` here to refer to `type-text-exercise` that are children of a `text-exercise-group`)

### Preparation / Checks / Precaution
- [x] Add cf-worker redirect from `GroupedExercise` to `ExerciseGroup`
- [x] Are there `GroupedExercise` that belong to more than one `ExerciseGroup`?
- [x] Generate and check list of `GroupedExercise` where the license is different than for the `ExerciseGroup` it belongs to
- [x] Check for `GroupedExercise` that are direct children of a taxonomy
- [x] Generate a list of uuids that use a `GroupedExercise` uuid  in "related content" or in a injection

### Tasks of the migration
- copy the editor state of each `GroupedExercise` into the new optional field of the parent `ExerciseGroup`
- like with the solutions also merge the revisions into the parent
- ~we can probably ignore the licenses (final desicion pending)~
- save `licenceId` of exercise into new state (at least if it's not a default license)

### exercise group state with exercises:
``` diff
 {
   "plugin": "type-text-exercise-group",
   …
   "state": {
    …
     "content": { ... },
+   "exercises": [{ 
+       "plugin": "exercise",
+       "state": { ... },
+       "id": "…"
+    }
+   …
+   ]
   },
   …
 }
```

### exercise state with optional `licenseId`
``` diff

{
   "plugin": "exercise",
   "state": {
     "content": …,
     "interactive": …,
     "solution": …
+    "licenseId": 1
   },
   "id": "…"
 }
```

### Rollout
- the migration itself can run anytime and should not cause problems in db-layer, api or frontend (only staging for now!)
- the frontend will then switch to displaying the "state-exercises" so we can already test the displaying of existing content
- the frontend has to then only allow creating of new child exercises inside the state (and not use an extra uuid any more)

### After
- we can then remove the GroupedExercise code from all repos (API, db-layer, cf-worker, frontend)
- and remove all GroupedExercises and revisions from the db in a follow up db-migration

**Comment by MoeHome** [comment]
>     * [ ]  Are there `GroupedExercise` that belong to more than one `ExerciseGroup`?
No, I used
`SELECT entity.id, COUNT(*)
FROM entity JOIN entity_link ON entity.id = entity_link.child_id
JOIN uuid ON uuid.id = entity.id WHERE entity.type_id = 5
AND uuid.trashed = 0 GROUP BY entity.id
HAVING COUNT(*) > 1;`
and got back an empty list.

**Comment by MoeHome** [comment]
>     * [ ]  Check for `GroupedExercise` that are direct children of a taxonomy
There are none.
`SELECT *
FROM entity
JOIN term_taxonomy_entity 
ON entity.id = term_taxonomy_entity.entity_id 
WHERE entity.type_id = 5;`
returns empty.

**Comment by MoeHome** [comment]
>     * [ ]  Generate and check list of `GroupedExercise` where the license is different than for the `ExerciseGroup` it belongs 
[List](https://github.com/serlo/db-migrations/files/14166792/related_exercisegroups_and_groupedexercises_with_different_licenses.ods)
generated by 
`SELECT entity.id AS GroupedExercise, entity.license_id, ent2.id AS ExerciseGroup, ent2.license_id 
FROM entity
JOIN entity_link ON entity.id = entity_link.child_id
JOIN entity ent2 ON entity_link.parent_id = ent2.id
JOIN uuid u1 ON u1.id = entity.id
JOIN uuid u2 ON u2.id = ent2.id
WHERE entity.type_id = 5 
AND NOT entity.license_id = ent2.license_id 
AND u1.trashed = 0 
AND u2.trashed = 0;
`

**Comment by MoeHome** [comment]
Do you want the trashed ones as well @elbotho ?

**Comment by kulla** [comment]
> Generate a list of uuids that use a GroupedExercise uuid in "related content" or in a injection

@MoeHome Here you can use https://nbviewer.org/github/serlo/evaluations/blob/main/src/2023/2023-11-02-injection-of-solutions.ipynb btw

**Comment by MoeHome** [comment]
>     * [ ]  Generate a list of uuids that use a `GroupedExercise` uuid  in "related content" or in a injection

In related content you can have articles, courses, videos and sources. I don't see a possibility to have a GroupedExercise here. Can you clarify what it is you are looking for here @elbotho ?

**Comment by elbotho** [comment]
> In related content you can have articles, courses, videos and sources. I don't see a possibility to have a GroupedExercise here. Can you clarify what it is you are looking for here @elbotho ?

there is a field in the `article` plugin for exercises that allows exercises:
`  exercises: list(child({ plugin: EditorPluginType.Injection })),`

**Comment by MoeHome** [comment]
[grouped_exercise_injections.csv](https://github.com/serlo/db-migrations/files/14210318/grouped_exercise_injections.csv)
These are all entities that use a GroupedExercise in an injection

**Comment by MoeHome** [comment]
And 
[this](https://github.com/serlo/db-migrations/files/14210519/grouped_exercise_injections.csv) is a list of all ExerciseGroups which are injected in entities.
